### ISSUE TITLE
PCRoom.users is empty even after subscribing

### ISSUE THREAD

**Issue by jain-ruchi** [pusher/chatkit-swift#116]
### What?

in `func onMessage(_ message: PCMessage)`:
`message.room.users` is coming back as an empty array (not always, but usually the first time `onMessage` is called for a room)

any ideas on what may be causing this issue and how we can work around it? this severely impacts our Inbox interface.

### Environment

* **PusherChatkit version:** 1.0.0
* **Xcode version:** 10.1
* **Swift version:** 4.1
* **Platform(s) running PusherChatkit:**

### Demo Project (if you have one; it helps a lot!)

----

CC @hamchapman

**Comment by mdpye** [comment]
The timing with the first message does appear to be glitchy. As both workaround (because this race condition is definitely a bug), but also as a more convenient approach generally, the SDK attaches a `PCUser` object to each `PCMessage` as the `sender` property. If you are rendering the senders of messages, I recommend using this property. It shouldn't suffer from the timing glitch you see in the room members.

The problem with the room membership being empty appears to be that we may emit `onMessage` before we have fully initialised the room subscription.
That's an issue which we will address, but if you do have cause to use the room members, you should wait until the `subscribeToRoom` completion handler has fired - that signals that the state has been populated fully.

**Comment by jain-ruchi** [comment]
Using the sender property in `PCMessage` only gets us one chat member at a time (we would have to accumulate this which is a lot of effort)

A workaround we are attempting instead is to call `fetchMessagesFrom` in the completion block of `subscribeToRoom` -- instead of setting message limit = 1 in `subscribe` and using `onMessage` where we are seeing the issue.

**Comment by jain-ruchi** [comment]
@mdpye the above attempt appears to have resolved our blocker!
