### ISSUE TITLE
onNewCursor not working for our app

### ISSUE THREAD

**Issue by hitchingsh** [pusher/chatkit-swift#121]
### What?

In our RoomVC.swift file we define the function onNewCursor ton the PCRoomDelegate which never gets called by Chatkit but should (this is the bug):

    func onNewCursor(cursor: PCCursor) {
        print("Cursor set for \(cursor.user.displayName) at position \(cursor.position)")
    }

and in onMessage we call

self.setCursor(with: self.room.id, messageId: message.id)

and we set this up in our subscribeTo call to RoomVC which is called when we enter a chat room:

    fileprivate func subscribeTo(room:PCRoom) {
        
        NSLog("SubscribingToRoom \(room.name) - if not successful then either private room or chatkit server error")

        //dont load any previous messages here
        self.currentUser.subscribeToRoom(id: room.id, roomDelegate: self, messageLimit: 0) { error in

            guard error == nil else {
                print("Error creating room: \(String(describing: error?.localizedDescription))")
                return
            }
            
            NSLog("Successfully subscribed room called \(String(describing: room.name))")
            self.postSubscribeProcess(room: room)
            
        }
    }

### Environment

MacOS 10.13.6

* **PusherChatkit version:**

  - PusherChatkit (1.2.3):
    - BeamsChatkit (~> 1.2)
    - PusherPlatform (~> 0.6)
  - PusherPlatform (0.6.2)
  - PusherSwift (6.1.0):

* **Xcode version:**

Version 10.1 (10B61)

* **Swift version:**

4.1

* **Platform(s) running PusherChatkit:**

### Demo Project (if you have one; it helps a lot!)

----

CC @hamchapman

**Comment by hamchapman** [comment]
It definitely should be being called. There are tests in the SDK for it.

The only thing I can spot that it _could_ be is that your function signature is 

```swift
func onNewCursor(cursor: PCCursor)
``` 

whereas the one used in the example and in the SDK tests is

```swift
func onNewCursor(_ cursor: PCCursor)
```

as seen here: https://github.com/pusher/chatkit-swift/blob/aa02a4681684bb58b71f2e6c5e536d1ae99bd882/Tests/Helpers/TestingDelegates.swift#L101

If the `_` being present is indeed the problem then that's unfortunate and I'd have thought would be something that Xcode would help with by hinting that you've got a function that nearly fulfils a protocol function's signature.

Let me know if that fixes it for you, otherwise we'll need more info about the steps that you're going through in order to hit the bug.

Thanks!
