### ISSUE TITLE
New PCRoomDelegate method

### ISSUE THREAD

**Issue by jjatie** [pusher/chatkit-swift#139]
### What?
When subscribing to a room, the only spot you get to respond to the subscription is in the completion handler of `subscribeToRoom` method. To maintain a separation of responsibilities, the delegate object is separate from the controller that wraps a PCRoom. This allows to swap out delegates based on the local store I'm using pretty easily.

My problem is that when subscribing to a room, I always want to immediately fetch all messages since the last one I have stored locally. A good spot to do this is in the delegate object which already knows about Core Data, and knows what the last messages stored locally were. In order to do this, I find my self making a `MyCoreDataRoomDelegate.user(_ user: PCCurrentUser, didSubscribeTo: PCRoom)` method and calling that in the completion handler.

I can't decide if this is an issue with the delegate, or that fetching messages since the last one received (a common task to want to do after subscribing to a room), but this is one potential solution.

### Environment

* **PusherChatkit version:** 1.2.3
* **Xcode version:** 10.1
* **Swift version:** 4.2
* **Platform(s) running PusherChatkit:** iOS 12.x

### Demo Project (if you have one; it helps a lot!)

----

CC @hamchapman

**Comment by mdpye** [comment]
Could you offer a little more detail on how you're storing messages locally?

Internally, we have a method which subscribes to a room and retrieves messages *since a particular message* rather than the last `x` messages. We use it to catch up after a client has been disconnected from the network during a session.

It's not exposed, for a couple of reasons

- there is still a limit to the number of messages retrievable this way - it's intended to catch up over short periods of disconnection, not e.g. days or weeks (or even hours, if it's a busy room)
- messages are keyed on an `eventID` which is separate from the message ID (e.g. if a message is updated, thats a new event, but the same message), and this is not currently exposed to the upper layers of the SDK either, because it has the potential to cause significant confusion

However, with some details of your use case, we could start to consider ways of exposing this functionality in the public API, so that if you are maintaining local storage of the client state, you can get a seamless resume by providing a "last received" key to the initial `subscribeToRoom` call, eliminating the need to communicate back.

In the mean time, what you are doing seems reasonable, if not convenient.
