### ISSUE TITLE
Crash in     @objc public func registerDeviceToken(_ deviceToken: Data, completion: @escaping () -> Void = {}) {

### ISSUE THREAD

**Issue by clay-mindoula** [pusher/chatkit-swift#140]
### What?
App crashed:
Thread 9: EXC_BREAKPOINT (code=1, subcode=0x103e0fdf0)
Method: registerDeviceToken
Line: strongSelf.preIISOperationQueue.resume()

Xcode was running a build on a device and this happened during startup, twice now.

### Environment

* **PusherChatkit version:** 1.3.0
* **Xcode version:**Version 10.1 (10B61)
* **Swift version:** 4.2.1
* **Platform(s) running PusherChatkit:**iOS

### Demo Project (if you have one; it helps a lot!)

----

CC @hamchapman

**Comment by sanjukta-navsoft** [comment]
I also face this issue

**Comment by clay-mindoula** [comment]
chatkit is flake (er) in debug fyi

**Comment by OliverPearmain-Pusher** [comment]
Since this relates to an older version of the SDK and because we haven't heard anything further in some time I am going to close this issue. Please re-open with more details if this is still an issue on the latest version.

Dedicated support is always available at https://support.pusher.com and support@pusher.com.
