### ISSUE TITLE
Leaving a group prevents new connections. 

### ISSUE THREAD

**Issue by papanton** [pusher/chatkit-swift#145]
### What?
Connecting with a user, creating a room and then leaving it using:
`
 currentUser?.leaveRoom(id: room.id, completionHandler: { error in
      log.info(error)
    })
`

I get the following error log, and any subsequent manager.connect() launches are not completed:

`Response received with status code 401. Error message: services/chatkit_authorizer/authorization/room_membership_required: Room membership required. Response: <NSHTTPURLResponse: 0x6000008c6140> { URL: https://us1.pusherplatform.io/services/chatkit/v2/19d7617d-213a-40e6-9c3c-63ca4b51836d/rooms/19404420 }`

Creates subscription issues
### Environment

* **PusherChatkit version:** 1.3.0
* **Xcode version:** 10.0
* **Swift version:** 4.
* **Platform(s) running PusherChatkit:**

### Demo Project (if you have one; it helps a lot!)

----

CC @hamchapman

**Comment by OliverPearmain-Pusher** [comment]
Since this relates to an older version of the SDK and because we haven't heard anything further in some time I am going to close this issue. Please re-open with more details if this is still an issue on the latest version.

Dedicated support is always available at https://support.pusher.com and support@pusher.com.
