### ISSUE TITLE
Cursors to deleted rooms sent to client

### ISSUE THREAD

**Issue by hitchingsh** [pusher/chatkit-swift#150]
### What?

If a room is deleted, cursors containing the room are still sent to the room which tries to fetch them.  This causes warning messages in the client and delays

### Environment

iOS 1.2.3
* **PusherChatkit version:**
* **Xcode version:**
* **Swift version:**
* **Platform(s) running PusherChatkit:**

### Demo Project (if you have one; it helps a lot!)

----

**Comment by OliverPearmain-Pusher** [comment]
Since this relates to an older version of the SDK and because we haven't heard anything further in some time I am going to close this issue. Please re-open with more details if this is still an issue on the latest version.

Dedicated support is always available at https://support.pusher.com and support@pusher.com.
