### ISSUE TITLE
Sometimes crash at establishUserSubscription

### ISSUE THREAD

**Issue by populius** [pusher/chatkit-swift#169]
### What?
Somtimes app crashes with "Fatal error: Attempted to read an unowned reference but object 0x282315ae0 was already deallocated"

### Environment

* **PusherChatkit version:** 1.4.2
* **Xcode version:** 10.1
* **Swift version:** 4.2
* **Platform(s) running PusherChatkit:**

### Demo Project (if you have one; it helps a lot!)

![Снимок экрана 2019-03-29 в 14 56 27](https://user-images.githubusercontent.com/2752484/55217850-1c1d4200-5233-11e9-836a-e858fabcf3db.png)

----

**Comment by vivangkumar** [comment]
Hi @populius Are you keeping a strong reference to the `ChatManager` object in your app?

**Comment by populius** [comment]
@vivangkumar Yes. For me this crash happen when init/connect ChatManager in airplane mode

**Comment by vivangkumar** [comment]
@populius I see! And does this consistently crash? If that's the case, I can try replicating this and fixing it.

**Comment by populius** [comment]
@vivangkumar yep

**Comment by sanjukta-navsoft** [comment]
Yes I also face same issue.

**Comment by vivangkumar** [comment]
I'll schedule some time later this week to take a deeper look at this.

**Comment by mastermind-app** [comment]
was this ever resolved? any guidance would be appreciated!

**Comment by lordweimer91** [comment]
I have the same problem. Is there any solution?

**Comment by artursDerkintis** [comment]
Same here - crashes almost every time app goes in background

**Comment by ben-pusher** [comment]
The issue described here is often caused by iOS collecting the `ChatManager` object. To overcome this you must maintain a strong reference to the object to prevent it being collected, as @vivangkumar has mentioned. 

The issue can also occur if your application creates a second `ChatManager` object. When this happens the first is deallocated and the new object replaces it. When this happens the application will continue to try and access the first `ChatManager` instance, however it will find that it no longer exists and the error will be encountered.  A typical example of this would be creating a new Chatkit object when the app state changes from background to foreground, or vice versa.

**Comment by OliverPearmain-Pusher** [comment]
Since this relates to an older version of the SDK and because we haven't heard anything further in some time I am going to close this issue. Please re-open with more details if this is still an issue on the latest version.

Dedicated support is always available at https://support.pusher.com and support@pusher.com.
