### ISSUE TITLE
logout

### ISSUE THREAD

**Issue by lordweimer91** [pusher/chatkit-swift#200]
### What?
How can I logout user?
If I do ChatManager.disconnect() and then login new user, I get messages as if I are a new user, but send from old user.

### Environment

* **PusherChatkit version:** (1.7.3)
* **Xcode version:** 10.3
* **Swift version:** 5.0
----

**Comment by OliverPearmain-Pusher** [comment]
Since this relates to an older version of the SDK and because we haven't heard anything further in some time I am going to close this issue. Please re-open with more details if this is still an issue on the latest version.

Dedicated support is always available at https://support.pusher.com and support@pusher.com.
